"""JAHIS電子版お薬手帳データフォーマット(JAHIS TC)ライブラリ。

- QRコード/テキスト -> 構造化データ: :func:`parse` / :func:`read_notebook_from_pngs`
- 構造化データ -> テキスト/QRコード: :func:`serialize` / :func:`encode_notebook_to_pngs`

対象仕様: JAHIS電子版お薬手帳データフォーマット仕様書 Ver.2.6 (バージョン情報 ``JAHISTC08``)
"""

from __future__ import annotations

from .issues import (
    Issue,
    IssueCode,
    IssueCollector,
    IssueLevel,
    MedicationNotebookError,
    ParseError,
    QrCodeError,
    SerializeError,
)
from .models import (
    Dispensing,
    DispensingInstitution,
    DispensingStaff,
    DoctorGroup,
    Drug,
    DrugContext,
    FamilyPharmacist,
    MedicationNotebook,
    NotebookMemo,
    OtcDrug,
    OtcDrugIngredient,
    Patient,
    PatientEntry,
    PatientRemark,
    PrescribingDoctor,
    PrescribingInstitution,
    ProvidedInfo,
    RawRecord,
    Rp,
    RpContext,
    SplitControl,
    TextNote,
    UnknownRecord,
    Usage,
    collect_drugs,
    collect_rps,
)
from .parser import ParseResult, parse, parse_or_raise
from .qr import (
    DEFAULT_ENCODING,
    DEFAULT_MAX_BYTES_PER_SYMBOL,
    MergeResult,
    ReadResult,
    byte_length,
    decode_all_qr_from_image,
    decode_all_qr_from_png,
    decode_qr_from_image,
    decode_qr_from_png,
    decode_text,
    encode_notebook_to_data_uris,
    encode_notebook_to_pngs,
    encode_notebook_to_svgs,
    encode_text,
    encode_text_to_data_uri,
    encode_text_to_png,
    encode_text_to_svg,
    make_qr,
    merge_split_parts,
    read_notebook_from_images,
    read_notebook_from_pngs,
    read_notebook_from_texts,
    split_for_qr,
    to_qr_text,
    to_qr_texts,
    unencodable_characters,
)
from .serializer import serialize, to_record_lines
from .spec.codes import CODE_TABLES, CodeTable, describe_code, is_valid_code
from .spec.records import (
    RECORD_SPECS,
    VERSION_RECORD_SPEC,
    Direction,
    FieldSpec,
    FieldType,
    RecordKind,
    RecordNo,
    RecordSpec,
    RequiredKind,
    direction_of,
    find_record_spec,
    record_spec_of,
)
from .spec.version import (
    DEFAULT_VERSION,
    FORMAT_VERSIONS,
    TARGET_SPEC_VERSION,
    FormatVersionInfo,
    find_format_version,
    is_version_record,
    spec_versions_of,
    version_number_of,
)
from .text import (
    EOF_CHARACTER,
    FIELD_SEPARATOR,
    RECORD_SEPARATOR,
    field_at,
    format_record,
    parse_raw_records,
    sjis_byte_length,
)
from .validation import ValidationOptions, is_valid_date, validate_record

__version__ = "0.1.0"

__all__ = [
    "CODE_TABLES",
    "DEFAULT_ENCODING",
    "DEFAULT_MAX_BYTES_PER_SYMBOL",
    "DEFAULT_VERSION",
    "EOF_CHARACTER",
    "FIELD_SEPARATOR",
    "FORMAT_VERSIONS",
    "RECORD_SEPARATOR",
    "RECORD_SPECS",
    "TARGET_SPEC_VERSION",
    "VERSION_RECORD_SPEC",
    "CodeTable",
    "Direction",
    "Dispensing",
    "DispensingInstitution",
    "DispensingStaff",
    "DoctorGroup",
    "Drug",
    "DrugContext",
    "FamilyPharmacist",
    "FieldSpec",
    "FieldType",
    "FormatVersionInfo",
    "Issue",
    "IssueCode",
    "IssueCollector",
    "IssueLevel",
    "MedicationNotebook",
    "MedicationNotebookError",
    "MergeResult",
    "NotebookMemo",
    "OtcDrug",
    "OtcDrugIngredient",
    "ParseError",
    "ParseResult",
    "Patient",
    "PatientEntry",
    "PatientRemark",
    "PrescribingDoctor",
    "PrescribingInstitution",
    "ProvidedInfo",
    "QrCodeError",
    "RawRecord",
    "ReadResult",
    "RecordKind",
    "RecordNo",
    "RecordSpec",
    "RequiredKind",
    "Rp",
    "RpContext",
    "SerializeError",
    "SplitControl",
    "TextNote",
    "UnknownRecord",
    "Usage",
    "ValidationOptions",
    "__version__",
    "byte_length",
    "collect_drugs",
    "collect_rps",
    "decode_all_qr_from_image",
    "decode_all_qr_from_png",
    "decode_qr_from_image",
    "decode_qr_from_png",
    "decode_text",
    "describe_code",
    "direction_of",
    "encode_notebook_to_data_uris",
    "encode_notebook_to_pngs",
    "encode_notebook_to_svgs",
    "encode_text",
    "encode_text_to_data_uri",
    "encode_text_to_png",
    "encode_text_to_svg",
    "field_at",
    "find_format_version",
    "find_record_spec",
    "format_record",
    "is_valid_code",
    "is_valid_date",
    "is_version_record",
    "make_qr",
    "merge_split_parts",
    "parse",
    "parse_or_raise",
    "parse_raw_records",
    "read_notebook_from_images",
    "read_notebook_from_pngs",
    "read_notebook_from_texts",
    "record_spec_of",
    "serialize",
    "sjis_byte_length",
    "spec_versions_of",
    "split_for_qr",
    "to_qr_text",
    "to_qr_texts",
    "to_record_lines",
    "unencodable_characters",
    "validate_record",
    "version_number_of",
]
